spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: spqjekdl1004
    password: qavviarwxcmvobmm
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부

  datasource:
    url: jdbc:mysql://jenson-db:3306/jenson?serverTimezone=Asia/Seoul
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

security:
  jwt:
    token:
      secret-key: s8R$kQz3nZ!L5pT7c@J#xM9vB1&uD6hE
      access:
        expire-length: 6000000 # 100 분